apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:7.0.5
          name: mongodb
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                    name: mongo-config
                    key: mongo_initdb_root_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongo-secret
                    key: mongo_initdb_root_password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                    name: mongo-config
                    key: mongo_initdb_database
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
    - name: 27017-27017
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
data:
  mongo_initdb_root_password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: mongo-secret
---
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongodb
---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 1Gi
---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
    mongo_initdb_database: 'product-service2'
    mongo_initdb_root_username: 'root'


